variables:
  IMAGE_TAG: latest
  QUICKLISP_ADD_TO_INIT_FILE: "true"
  QUICKLISP_DIST_VERSION: latest

image: clfoundation/$LISP:$IMAGE_TAG

stages:
  - test

before_script:
  - install-quicklisp

.test:
  stage: test
  script:
    - make test

sbcl test:
  extends: .test
  variables:
    LISP: sbcl